baseurl = "https://glitchbra.in" # Controls base URL
languageCode = "en-UK" # Controls site language
# title = "Short-circuits and digressions" # Homepage title and page title suffix
paginate = 20 # Number of posts to show before paginating
theme = "hello-friend-ng" # Set default theme
enableRobotsTXT = true # Suggested, enable robots.txt file
SectionPagesMenu = "main" # Enable menu system for lazy bloggers
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link

[params]
  defaultTheme = "dark"
  homeSubTitle = "Short-circuits and digressions"
  customCSS = ["/css/tooltip.css"]
  footerRight = "<a href=\"https://cs-web.swan.ac.uk/~cpradic/\"> <~</a> Webring du Brocoli <a href=\"https://www.zapashcanon.fr/\"> ~></a>"
  [portrait]
    path = "/Hecate-yellow.png"

[markup.goldmark.renderer]
  unsafe = true

[[params.social]]
  name = "twitter"
  url  = "https://twitter.com/TechnoEmpress"
[[params.social]]
  name = "github"
  url  = "https://github.com/Kleidukos"
[[params.social]]
  name = "mastodon"
  url  = "https://merveilles.town/@hecate"
[[params.social]]
  name = "ko-fi"
  url  = "https://ko-fi.com/HecateMoonlight"


[languages]
  [languages.en]
    title = "Hécate's blog"
    subtitle = "Short-circuits and digressions"
    keywords = ""
    readOtherPosts = ""

    [languages.en.params.logo]
      logoText = "cd ~/"
      logoHomeLink = "/"
